services:
  app:
    container_name: job_portal
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mongodb://admin:qwerty@mongo:27017/?authSource=admin
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qwerty
    depends_on:
      - mongo

volumes:
  mongo_data:
